import {
  PERSONA_DETALLES,
  CONSULTAS_DETALLES,
  DIAGNOSTICO_DETALLES,
  EXAMENES_DETALLES,
  MEDICAMENTOS_DETALLES,
  TRATAMIENTOS_DETALLES,
  EMERGENCIA_DETALLES,
  HOSPITALIZACION_DETALLES,
  DOCTOR_DETALLES
} from "./user";
